사용금액 input 리팩토링
prgrms-web-devcourse/Team-5YES-WuMo-FE pull request #231
Opened 2023-04-13 10:17 UTC by YJZero

## 💡 Linked Issues

Resolve: #230

## 📖 구현 내용
- 기존에 포맷터 적용하면서 react-hook-form으로 관리하지 못했던 input을 react-hook-form에서 관리하면서 포맷터를 적용하도록 수정하였습니다.
- api 파일에서 try catch 로 잡던 에러를 해당 컴포넌트에서 잡을 수 있도록 수정하였습니다.

## 🖼 구현 이미지
없음

## ✅ PR 포인트 & 궁금한 점

2023-04-14 09:15 UTC, chunwookJoo commented on src/components/party/schedule/routeComment/placeAmount/PlaceAmountField.tsx
> +          control={control}
ask;
Controller를 사용한 이유가 혹시 있나요?? 단순히 리렌더링만 막기 위함이라면 input태그에 register를 적용해도 좋을것같아요! (민재형이 알려줌)

2023-04-14 11:14 UTC, YJZero commented on src/components/party/schedule/routeComment/placeAmount/PlaceAmountField.tsx
> +          control={control}
register를 사용해봤는데 아래 같은 코드로 작성했어요!
```tsx
        <InputGroup size='sm' maxW='12.5rem'>
          <InputLeftElement
            pointerEvents='none'
            color='gray'
            fontSize='1.5625rem'
            ml='0.25rem'>
            <MdCreditCard />
          </InputLeftElement>
          <Input
            type='text'
            value={formatPrice(Number(watch('amount')))}
            borderRadius='0.9375rem'
            placeholder='사용 금액을 입력하세요'
            {...register('amount', {
              onChange: ({ target }) => {
                const value = target.value.replace(/[^0-9]/g, '');
                setValue('amount', value);
              },
            })}
          />
          <InputRightElement>원</InputRightElement>
        </InputGroup>
 ```

그런데 실시간으로 값을 다시 포맷하기 위해 watch를 사용해서 전체 컴포넌트가 리렌더링이 되더라구요! 포맷터 적용을 위해서 다시 value를 설정해주는 과정이 필요한데 register를 사용할 때 실시간 값을 watch 말고는 어떤 방법으로 가져올 수 있을지 모르겠네용ㅠㅠ 그래서 Controller를 사용했는데 혹시 아신다면 공유해주시면 감사하겠습니다~~

2023-04-15 12:56 UTC, mxx-kor requested changes
react hook form으로 리팩토링 하시는거 멋집니다 ㅎㅎ

2023-04-15 12:56 UTC, mxx-kor commented on src/components/party/schedule/routeComment/placeAmount/PlaceAmountField.tsx
> +          control={control}
일단 validation을 위해서 watch를 사용하시는것 같아요! onChange를 사용하셔서 그런데 register에서 제공하는 메서드인  
```
<input
  type="number"
  {...register("test", {
    valueAsNumber: true,
  })}
/>
``` 
로 숫자만 입력되도록하고 onChange를 빼주세요!

2023-04-17 08:01 UTC, YJZero commented on src/components/party/schedule/routeComment/placeAmount/PlaceAmountField.tsx
> +          control={control}
오옹 바로 시도해보겠습니다 👍👍

2023-04-17 08:15 UTC, YJZero commented on src/components/party/schedule/routeComment/placeAmount/PlaceAmountField.tsx
> +          control={control}
오오오 민재오빠 방법 완전 잘돼요👍👍혁명이군요 역시 react hook form 천재....

2023-04-17 11:48 UTC, mxx-kor approved these changes
리렌더링도 신경써주셔서 더 좋았어요~

2023-04-17 11:48 UTC, mxx-kor commented on src/components/party/schedule/routeComment/placeAmount/PlaceAmountField.tsx
> +            })}
더 깔끔해졌네요! 좋아요 수고하셨습니다~~

2023-04-17 12:31 UTC, glassk approved these changes
저도 참고해서 리팩토링해봐야겠어요! 넘 깔끔하네요 고생하셨어요 💯

2023-04-17 14:36 UTC, merged